-- MySQL Script generated by MySQL Workbench
-- Tue Feb 24 16:41:37 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cantinhos_bh
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cantinhos_bh
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cantinhos_bh` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `cantinhos_bh` ;

-- -----------------------------------------------------
-- Table `cantinhos_bh`.`cafeterias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cantinhos_bh`.`cafeterias` ;

CREATE TABLE IF NOT EXISTS `cantinhos_bh`.`cafeterias` (
  `id_cafeteria` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `endereco` VARCHAR(200) NULL DEFAULT NULL,
  `bairro` VARCHAR(100) NULL DEFAULT NULL,
  `cidade` VARCHAR(80) NOT NULL DEFAULT 'Belo Horizonte',
  `estado` CHAR(2) NOT NULL DEFAULT 'MG',
  `faixa_preco` ENUM('BAIXO', 'MEDIO', 'ALTO') NULL DEFAULT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `site` VARCHAR(200) NULL DEFAULT NULL,
  `instagram` VARCHAR(100) NULL DEFAULT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT '1',
  `criado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `atualizado_em` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_cafeteria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `idx_bairro` ON `cantinhos_bh`.`cafeterias` (`bairro` ASC) VISIBLE;

CREATE INDEX `idx_faixa_preco` ON `cantinhos_bh`.`cafeterias` (`faixa_preco` ASC) VISIBLE;

CREATE INDEX `idx_ativo` ON `cantinhos_bh`.`cafeterias` (`ativo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `cantinhos_bh`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cantinhos_bh`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `cantinhos_bh`.`usuarios` (
  `id_usuario` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NOT NULL,
  `email` VARCHAR(180) NOT NULL,
  `senha_hash` VARCHAR(255) NOT NULL,
  `tipo` ENUM('COMUM', 'PROPRIETARIO', 'ADMIN') NOT NULL DEFAULT 'COMUM',
  `criado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `atualizado_em` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `email` ON `cantinhos_bh`.`usuarios` (`email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `cantinhos_bh`.`avaliacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cantinhos_bh`.`avaliacoes` ;

CREATE TABLE IF NOT EXISTS `cantinhos_bh`.`avaliacoes` (
  `id_avaliacao` BIGINT NOT NULL AUTO_INCREMENT,
  `id_cafeteria` BIGINT NOT NULL,
  `id_usuario` BIGINT NOT NULL,
  `valor` TINYINT NOT NULL,
  `criado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_avaliacao`),
  CONSTRAINT `fk_av_cafeteria`
    FOREIGN KEY (`id_cafeteria`)
    REFERENCES `cantinhos_bh`.`cafeterias` (`id_cafeteria`),
  CONSTRAINT `fk_av_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `cantinhos_bh`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `uq_avaliacao_unica` ON `cantinhos_bh`.`avaliacoes` (`id_cafeteria` ASC, `id_usuario` ASC) VISIBLE;

CREATE INDEX `fk_av_usuario` ON `cantinhos_bh`.`avaliacoes` (`id_usuario` ASC) VISIBLE;

CREATE UNIQUE INDEX `id_cafeteria_UNIQUE` ON `cantinhos_bh`.`avaliacoes` (`id_cafeteria` ASC) VISIBLE;

CREATE UNIQUE INDEX `id_usuario_UNIQUE` ON `cantinhos_bh`.`avaliacoes` (`id_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `cantinhos_bh`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cantinhos_bh`.`categorias` ;

CREATE TABLE IF NOT EXISTS `cantinhos_bh`.`categorias` (
  `id_categoria` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `nome` ON `cantinhos_bh`.`categorias` (`nome` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `cantinhos_bh`.`cafeteria_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cantinhos_bh`.`cafeteria_categoria` ;

CREATE TABLE IF NOT EXISTS `cantinhos_bh`.`cafeteria_categoria` (
  `id_cafeteria` BIGINT NOT NULL,
  `id_categoria` BIGINT NOT NULL,
  PRIMARY KEY (`id_cafeteria`, `id_categoria`),
  CONSTRAINT `fk_cc_cafeteria`
    FOREIGN KEY (`id_cafeteria`)
    REFERENCES `cantinhos_bh`.`cafeterias` (`id_cafeteria`),
  CONSTRAINT `fk_cc_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `cantinhos_bh`.`categorias` (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_cc_categoria` ON `cantinhos_bh`.`cafeteria_categoria` (`id_categoria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `cantinhos_bh`.`estilos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cantinhos_bh`.`estilos` ;

CREATE TABLE IF NOT EXISTS `cantinhos_bh`.`estilos` (
  `id_estilo` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_estilo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `nome` ON `cantinhos_bh`.`estilos` (`nome` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `cantinhos_bh`.`cafeteria_estilo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cantinhos_bh`.`cafeteria_estilo` ;

CREATE TABLE IF NOT EXISTS `cantinhos_bh`.`cafeteria_estilo` (
  `id_cafeteria` BIGINT NOT NULL,
  `id_estilo` BIGINT NOT NULL,
  PRIMARY KEY (`id_cafeteria`, `id_estilo`),
  CONSTRAINT `fk_ce_cafeteria`
    FOREIGN KEY (`id_cafeteria`)
    REFERENCES `cantinhos_bh`.`cafeterias` (`id_cafeteria`),
  CONSTRAINT `fk_ce_estilo`
    FOREIGN KEY (`id_estilo`)
    REFERENCES `cantinhos_bh`.`estilos` (`id_estilo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_ce_estilo` ON `cantinhos_bh`.`cafeteria_estilo` (`id_estilo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `cantinhos_bh`.`tipos_cardapio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cantinhos_bh`.`tipos_cardapio` ;

CREATE TABLE IF NOT EXISTS `cantinhos_bh`.`tipos_cardapio` (
  `id_tipo` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `nome` ON `cantinhos_bh`.`tipos_cardapio` (`nome` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `cantinhos_bh`.`cafeteria_tipo_cardapio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cantinhos_bh`.`cafeteria_tipo_cardapio` ;

CREATE TABLE IF NOT EXISTS `cantinhos_bh`.`cafeteria_tipo_cardapio` (
  `id_cafeteria` BIGINT NOT NULL,
  `id_tipo` BIGINT NOT NULL,
  PRIMARY KEY (`id_cafeteria`, `id_tipo`),
  CONSTRAINT `fk_ctc_cafeteria`
    FOREIGN KEY (`id_cafeteria`)
    REFERENCES `cantinhos_bh`.`cafeterias` (`id_cafeteria`),
  CONSTRAINT `fk_ctc_tipo`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `cantinhos_bh`.`tipos_cardapio` (`id_tipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_ctc_tipo` ON `cantinhos_bh`.`cafeteria_tipo_cardapio` (`id_tipo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `cantinhos_bh`.`cupons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cantinhos_bh`.`cupons` ;

CREATE TABLE IF NOT EXISTS `cantinhos_bh`.`cupons` (
  `id_cupom` BIGINT NOT NULL AUTO_INCREMENT,
  `id_cafeteria` BIGINT NOT NULL,
  `titulo` VARCHAR(120) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `codigo` VARCHAR(40) NOT NULL,
  `data_inicio` DATETIME NOT NULL,
  `data_fim` DATETIME NOT NULL,
  `limite_total` INT NULL DEFAULT NULL,
  `limite_por_usuario` INT NOT NULL DEFAULT '1',
  `status` ENUM('RASCUNHO', 'PENDENTE', 'APROVADO', 'ATIVO', 'EXPIRADO', 'REJEITADO') NOT NULL DEFAULT 'PENDENTE',
  `id_proprietario` BIGINT NOT NULL,
  `id_admin_aprovador` BIGINT NULL DEFAULT NULL,
  `aprovado_em` DATETIME NULL DEFAULT NULL,
  `criado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_cupom`),
  CONSTRAINT `fk_cpn_admin`
    FOREIGN KEY (`id_admin_aprovador`)
    REFERENCES `cantinhos_bh`.`usuarios` (`id_usuario`),
  CONSTRAINT `fk_cpn_cafeteria`
    FOREIGN KEY (`id_cafeteria`)
    REFERENCES `cantinhos_bh`.`cafeterias` (`id_cafeteria`),
  CONSTRAINT `fk_cpn_propriet`
    FOREIGN KEY (`id_proprietario`)
    REFERENCES `cantinhos_bh`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `uq_codigo_por_cafe` ON `cantinhos_bh`.`cupons` (`id_cafeteria` ASC, `codigo` ASC) VISIBLE;

CREATE INDEX `fk_cpn_propriet` ON `cantinhos_bh`.`cupons` (`id_proprietario` ASC) VISIBLE;

CREATE INDEX `fk_cpn_admin` ON `cantinhos_bh`.`cupons` (`id_admin_aprovador` ASC) VISIBLE;

CREATE INDEX `idx_cpn_status` ON `cantinhos_bh`.`cupons` (`status` ASC) VISIBLE;

CREATE INDEX `idx_cpn_inicio` ON `cantinhos_bh`.`cupons` (`data_inicio` ASC) VISIBLE;

CREATE INDEX `idx_cpn_fim` ON `cantinhos_bh`.`cupons` (`data_fim` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `cantinhos_bh`.`destaques`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cantinhos_bh`.`destaques` ;

CREATE TABLE IF NOT EXISTS `cantinhos_bh`.`destaques` (
  `id_destaque` BIGINT NOT NULL AUTO_INCREMENT,
  `id_cafeteria` BIGINT NOT NULL,
  `id_proprietario` BIGINT NOT NULL,
  `plano` ENUM('BASICO', 'PLUS', 'PREMIUM') NOT NULL,
  `data_inicio` DATETIME NOT NULL,
  `data_fim` DATETIME NOT NULL,
  `status` ENUM('PENDENTE', 'APROVADO', 'ATIVO', 'EXPIRADO', 'REJEITADO') NOT NULL DEFAULT 'PENDENTE',
  `referencia_pagamento` VARCHAR(100) NULL DEFAULT NULL,
  `id_admin_aprovador` BIGINT NULL DEFAULT NULL,
  `aprovado_em` DATETIME NULL DEFAULT NULL,
  `criado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_destaque`),
  CONSTRAINT `fk_dst_admin`
    FOREIGN KEY (`id_admin_aprovador`)
    REFERENCES `cantinhos_bh`.`usuarios` (`id_usuario`),
  CONSTRAINT `fk_dst_cafeteria`
    FOREIGN KEY (`id_cafeteria`)
    REFERENCES `cantinhos_bh`.`cafeterias` (`id_cafeteria`),
  CONSTRAINT `fk_dst_propriet`
    FOREIGN KEY (`id_proprietario`)
    REFERENCES `cantinhos_bh`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_dst_cafeteria` ON `cantinhos_bh`.`destaques` (`id_cafeteria` ASC) VISIBLE;

CREATE INDEX `fk_dst_propriet` ON `cantinhos_bh`.`destaques` (`id_proprietario` ASC) VISIBLE;

CREATE INDEX `fk_dst_admin` ON `cantinhos_bh`.`destaques` (`id_admin_aprovador` ASC) VISIBLE;

CREATE INDEX `idx_dst_status` ON `cantinhos_bh`.`destaques` (`status` ASC) VISIBLE;

CREATE INDEX `idx_dst_inicio` ON `cantinhos_bh`.`destaques` (`data_inicio` ASC) VISIBLE;

CREATE INDEX `idx_dst_fim` ON `cantinhos_bh`.`destaques` (`data_fim` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `cantinhos_bh`.`favoritos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cantinhos_bh`.`favoritos` ;

CREATE TABLE IF NOT EXISTS `cantinhos_bh`.`favoritos` (
  `id_usuario` BIGINT NOT NULL,
  `id_cafeteria` BIGINT NOT NULL,
  `criado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_usuario`, `id_cafeteria`),
  CONSTRAINT `fk_fav_cafeteria`
    FOREIGN KEY (`id_cafeteria`)
    REFERENCES `cantinhos_bh`.`cafeterias` (`id_cafeteria`),
  CONSTRAINT `fk_fav_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `cantinhos_bh`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_fav_cafeteria` ON `cantinhos_bh`.`favoritos` (`id_cafeteria` ASC) VISIBLE;

CREATE UNIQUE INDEX `id_cafeteria_UNIQUE` ON `cantinhos_bh`.`favoritos` (`id_cafeteria` ASC) VISIBLE;

CREATE UNIQUE INDEX `id_usuario_UNIQUE` ON `cantinhos_bh`.`favoritos` (`id_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `cantinhos_bh`.`proprietario_cafeteria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cantinhos_bh`.`proprietario_cafeteria` ;

CREATE TABLE IF NOT EXISTS `cantinhos_bh`.`proprietario_cafeteria` (
  `id_usuario` BIGINT NOT NULL,
  `id_cafeteria` BIGINT NOT NULL,
  `criado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_usuario`, `id_cafeteria`),
  CONSTRAINT `fk_pc_cafeteria`
    FOREIGN KEY (`id_cafeteria`)
    REFERENCES `cantinhos_bh`.`cafeterias` (`id_cafeteria`),
  CONSTRAINT `fk_pc_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `cantinhos_bh`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_pc_cafeteria` ON `cantinhos_bh`.`proprietario_cafeteria` (`id_cafeteria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `cantinhos_bh`.`resgates_cupons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cantinhos_bh`.`resgates_cupons` ;

CREATE TABLE IF NOT EXISTS `cantinhos_bh`.`resgates_cupons` (
  `id_resgate` BIGINT NOT NULL AUTO_INCREMENT,
  `id_cupom` BIGINT NOT NULL,
  `id_usuario` BIGINT NOT NULL,
  `resgatado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_resgate`),
  CONSTRAINT `fk_resg_cupom`
    FOREIGN KEY (`id_cupom`)
    REFERENCES `cantinhos_bh`.`cupons` (`id_cupom`),
  CONSTRAINT `fk_resg_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `cantinhos_bh`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `uq_resgate_unico` ON `cantinhos_bh`.`resgates_cupons` (`id_cupom` ASC, `id_usuario` ASC) VISIBLE;

CREATE INDEX `fk_resg_usuario` ON `cantinhos_bh`.`resgates_cupons` (`id_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `cantinhos_bh`.`videos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cantinhos_bh`.`videos` ;

CREATE TABLE IF NOT EXISTS `cantinhos_bh`.`videos` (
  `id_video` BIGINT NOT NULL AUTO_INCREMENT,
  `id_cafeteria` BIGINT NOT NULL,
  `id_usuario` BIGINT NULL DEFAULT NULL,
  `plataforma` ENUM('TIKTOK', 'INSTAGRAM', 'YOUTUBE', 'OUTRO') NOT NULL,
  `url` VARCHAR(300) NOT NULL,
  `status` ENUM('PENDENTE', 'APROVADO', 'REJEITADO') NOT NULL DEFAULT 'PENDENTE',
  `destaque` TINYINT(1) NOT NULL DEFAULT '0',
  `id_admin_aprovador` BIGINT NULL DEFAULT NULL,
  `aprovado_em` DATETIME NULL DEFAULT NULL,
  `criado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_video`),
  CONSTRAINT `fk_vid_admin`
    FOREIGN KEY (`id_admin_aprovador`)
    REFERENCES `cantinhos_bh`.`usuarios` (`id_usuario`),
  CONSTRAINT `fk_vid_cafeteria`
    FOREIGN KEY (`id_cafeteria`)
    REFERENCES `cantinhos_bh`.`cafeterias` (`id_cafeteria`),
  CONSTRAINT `fk_vid_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `cantinhos_bh`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `fk_vid_cafeteria` ON `cantinhos_bh`.`videos` (`id_cafeteria` ASC) VISIBLE;

CREATE INDEX `fk_vid_usuario` ON `cantinhos_bh`.`videos` (`id_usuario` ASC) VISIBLE;

CREATE INDEX `fk_vid_admin` ON `cantinhos_bh`.`videos` (`id_admin_aprovador` ASC) VISIBLE;

CREATE INDEX `idx_vid_status` ON `cantinhos_bh`.`videos` (`status` ASC) VISIBLE;

CREATE INDEX `idx_vid_plataforma` ON `cantinhos_bh`.`videos` (`plataforma` ASC) VISIBLE;

CREATE INDEX `idx_vid_dest` ON `cantinhos_bh`.`videos` (`destaque` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
